export type OnboardingChapterId =
  | 'general'
  | 'companies'
  | 'connections'
  | 'templates'
  | 'chains'
  | 'campaign'
  | 'analytics';

export type OnboardingPlacement = 'top' | 'bottom' | 'left' | 'right';

export type OnboardingStepDefinition = {
  id: string;
  route: string;
  target?: string;
  title: string;
  description: string;
  details?: string[];
  tip?: string;
  placement?: OnboardingPlacement;
};

export type OnboardingChapterDefinition = {
  id: OnboardingChapterId;
  title: string;
  description: string;
  entryRoute: string;
  scope: 'general' | 'local';
  stepIds: string[];
};

// Version 8 introduces the complete document, chain, campaign and analytics
// chapters. A version bump is intentional so an interrupted older tour does not
// resume in the middle of a materially different chapter.
export const ONBOARDING_VERSION = 8;

// The original 22 records stay in their previous order so a paused session
// keeps pointing at the same step after the chaptered onboarding is deployed.
export const ONBOARDING_STEPS: OnboardingStepDefinition[] = [
  {
    id: 'welcome',
    route: '/',
    title: 'Добро пожаловать в ai offer',
    description: 'Общее обучение покажет путь от настройки системы до контроля первой рассылки. Ничего заполнять не нужно.',
  },
  {
    id: 'connection-open',
    route: '/connections',
    target: '[data-onboarding-id="add-connection"]',
    title: 'Подключение отправителя',
    description: 'Здесь администратор подключает SMTP, OAuth, RuSender или MailoPost. Подробные параметры разобраны в обучении «Подключения».',
    placement: 'bottom',
  },
  {
    id: 'connection-method',
    route: '/connections',
    target: '[data-onboarding-id="connection-method"] .ant-form-item-label > label',
    title: 'Способ отправки',
    description: '«Почтовый ящик» использует SMTP или OAuth, а «API-ключ» подключает RuSender либо MailoPost.',
    placement: 'right',
  },
  {
    id: 'connection-details',
    route: '/connections',
    target: '[data-onboarding-id="connection-details"] .ant-steps-item:first-child .ant-steps-item-title',
    title: 'Адрес и параметры почтового ящика',
    description: 'По домену email сервис определяет провайдера и предлагает подходящий способ входа и настройки SMTP.',
    placement: 'right',
  },
  {
    id: 'connection-auth',
    route: '/connections',
    target: '[data-onboarding-id="connection-auth"] .ant-form-item-label > label',
    title: 'Тип входа',
    description: 'Обычный пароль, пароль приложения или OAuth выбираются по требованиям почтового провайдера.',
    placement: 'right',
  },
  {
    id: 'connection-api-provider',
    route: '/connections',
    target: '[data-onboarding-id="connection-api-provider"] .ant-form-item-label > label',
    title: 'Провайдер API',
    description: 'Здесь выбирается RuSender или MailoPost. От провайдера зависят формат ключа, адрес API и доступные статусы доставки.',
    placement: 'right',
  },
  {
    id: 'connection-credentials',
    route: '/connections',
    target: '[data-onboarding-id="connection-credentials"] .ant-form-item:first-child .ant-form-item-label > label',
    title: 'Данные доступа',
    description: 'Токен даёт доступ к отправке, а подтверждённый email используется как адрес отправителя. Секреты сохраняются в защищённом виде.',
    placement: 'right',
  },
  {
    id: 'connection-submit',
    route: '/connections',
    target: '[data-onboarding-id="connection-submit"]',
    title: 'Проверка подключения',
    description: 'Кнопка проверяет реквизиты и сохраняет отправителя. В пассивном режиме обучения запрос не выполняется.',
    placement: 'top',
  },
  {
    id: 'connection-limits',
    route: '/connections',
    target: '[data-onboarding-id="connection-rate-limits"]',
    title: 'Лимиты отправки',
    description: 'Почасовой и дневной лимиты ограничивают общий поток этого подключения во всех рассылках.',
    placement: 'right',
  },
  {
    id: 'template-open',
    route: '/templates',
    target: '[data-onboarding-id="add-template"]',
    title: 'Шаблоны писем и документов',
    description: 'Перед рассылкой создаются письма и, при необходимости, вложения. Подробный обзор доступен в обучении «Шаблоны».',
    placement: 'bottom',
  },
  {
    id: 'template-format',
    route: '/templates',
    target: '[data-onboarding-id="template-format"] .ant-card:first-child h5',
    title: 'Формат письма',
    description: 'Простое письмо подходит для текста, HTML — для сложного дизайна, а загрузка переносит основу из готового файла.',
    placement: 'right',
  },
  {
    id: 'template-source',
    route: '/templates',
    target: '[data-onboarding-id="template-source"] .starter-tile:first-child',
    title: 'Основа шаблона',
    description: 'Можно взять готовый пример, начать с пустого шаблона или загрузить исходный документ.',
    placement: 'right',
  },
  {
    id: 'template-custom',
    route: '/templates',
    target: '[data-onboarding-id="template-custom"] > div:first-child .ant-typography',
    title: 'Генерация письма',
    description: 'Модель определяет способ генерации, описание задаёт содержание, а файлы добавляют исходные материалы.',
    placement: 'right',
  },
  {
    id: 'campaign-basics',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-wizard"] .ant-collapse-item-active [data-onboarding-id="campaign-step-basics-label"]',
    title: 'Рассылка, цепочка и компания',
    description: 'Название идентифицирует рассылку. Цепочка задаёт письма и переходы, а компания и вид работ управляют бизнес-контекстом и персонализацией.',
    placement: 'right',
  },
  {
    id: 'campaign-sender',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-wizard"] .ant-collapse-item-active [data-onboarding-id="campaign-step-sender-label"]',
    title: 'Отправитель',
    description: 'Выбранное подключение определяет адрес, транспорт, лимиты и правила защиты доставки. Отправитель по умолчанию может подставляться автоматически.',
    placement: 'right',
  },
  {
    id: 'campaign-recipients',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-wizard"] .ant-collapse-item-active [data-onboarding-id="campaign-step-recipients-label"]',
    title: 'Получатели',
    description: 'Получателей берут из сохранённой аудитории, загружают из Excel/CSV или генерируют. Перед запуском проверяются адреса и исключения.',
    placement: 'right',
  },
  {
    id: 'campaign-schedule',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-wizard"] .ant-collapse-item-active [data-onboarding-id="campaign-step-schedule-label"]',
    title: 'Расписание и скорость',
    description: 'Дата старта, размер пакета и интервал определяют длительность рассылки и нагрузку на выбранное подключение.',
    placement: 'right',
  },
  {
    id: 'campaign-launch',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-wizard"] .ant-collapse-item-active [data-onboarding-id="campaign-step-launch-label"]',
    title: 'Проверка и запуск',
    description: 'До старта система проверяет обязательные разделы, переменные, документы, получателей и тестовое письмо. Обучение ничего не запускает.',
    placement: 'right',
  },
  {
    id: 'statistics-overview',
    route: '/',
    target: '[data-onboarding-id="statistics-summary"]',
    title: 'Результаты рассылок',
    description: 'Сводка показывает приём провайдером, доставку, открытия, переходы, ошибки и согласия. Детали разобраны в главе «Контроль и аналитика».',
    placement: 'bottom',
  },
  {
    id: 'campaigns-overview',
    route: '/?tab=campaign-list',
    target: '[data-onboarding-id="campaigns-overview"] .ant-table-thead th:first-child',
    title: 'Управление рассылками',
    description: 'Здесь видны состояние, прогресс, ошибки и доступные действия: открыть, поставить на паузу, продолжить или отменить.',
    placement: 'top',
  },
  {
    id: 'chains-overview',
    route: '/chains',
    target: '[data-onboarding-id="chains-list"] .ant-table-thead',
    title: 'Библиотека цепочек',
    description: 'Цепочки хранят последовательности писем и ссылок. Черновик можно редактировать, а опубликованную цепочку — использовать в рассылке.',
    placement: 'bottom',
  },
  {
    id: 'finish',
    route: '/',
    title: 'Общее обучение завершено',
    description: 'Система не создала и не изменила бизнес-данные. Тематические обучения можно открыть в любой момент по кнопке «?».',
  },

  {
    id: 'quick-chain',
    route: '/chains',
    target: '[data-onboarding-id="create-chain"]',
    title: 'Цепочка писем',
    description: 'Цепочка связывает письма, документы и переходы. Подробно конструктор разобран в отдельном обучении «Цепочки».',
    placement: 'bottom',
  },
  {
    id: 'admin-intro',
    route: '/companies',
    title: 'Настройка администратора',
    description: 'Глава показывает параметры, которые влияют на доступные сценарии, отправку, скорость и реакцию системы на ошибки.',
  },
  {
    id: 'company-overview',
    route: '/companies',
    target: '[data-onboarding-id="companies-overview"]',
    title: 'Компании',
    description: 'Компания объединяет участников, виды работ и фирменные данные. Она также задаёт бизнес-контекст при создании рассылки.',
    placement: 'bottom',
  },
  {
    id: 'company-details',
    route: '/companies',
    target: '[data-onboarding-id="company-details"] .ant-form-item:first-child .ant-form-item-label > label',
    title: 'Карточка компании',
    description: 'Название участвует в выборе компании, контакты помогают администрированию, а логотип используется в интерфейсе и фирменных материалах.',
    placement: 'right',
  },
  {
    id: 'company-work-types',
    route: '/companies',
    target: '[data-onboarding-id="company-work-types"]',
    title: 'Виды работ',
    description: 'Вид работ выбирается в рассылке и может подставляться в письмо или документ. Изменения в этом списке сохраняются автоматически.',
    placement: 'bottom',
  },
  {
    id: 'connection-delivery-guard',
    route: '/connections',
    target: '[data-onboarding-id="connection-delivery-guard"]',
    title: 'Защита доставки',
    description: 'Порог ошибок, окно расчёта и минимальная выборка определяют, когда активные рассылки будут поставлены на паузу и начнётся прогрев.',
    placement: 'right',
  },
  {
    id: 'profile-defaults',
    route: '/profile?tab=defaults',
    target: '[data-onboarding-id="profile-defaults"] .ant-form-item .ant-form-item-label > label',
    title: 'Настройки рассылок по умолчанию',
    description: 'Тема и размер пакета по умолчанию ускоряют создание рассылок, но их всегда можно изменить в конкретной кампании.',
    placement: 'bottom',
  },
  {
    id: 'profile-notifications',
    route: '/profile?tab=notifications',
    target: '[data-onboarding-id="profile-notifications"] .ant-form-item .ant-form-item-label > label',
    title: 'Операционные уведомления',
    description: 'Уведомления о завершении и ошибках помогают администратору вовремя проверить результат или вмешаться в отправку.',
    placement: 'bottom',
  },
  {
    id: 'admin-finish',
    route: '/connections',
    title: 'Настройка администратора завершена',
    description: 'Вы просмотрели компании, виды работ, подключения, лимиты, защиту доставки и параметры уведомлений. Ничего не было сохранено.',
  },

  {
    id: 'content-intro',
    route: '/templates',
    title: 'Шаблоны',
    description: 'Обучение показывает библиотеку писем, документы, генерацию, редактирование и предпросмотр.',
  },
  {
    id: 'template-library',
    route: '/templates',
    target: '[data-onboarding-id="template-library-toolbar"]',
    title: 'Библиотека писем',
    description: 'Карточки показывают формат и состояние шаблона. Отсюда письмо редактируют, просматривают, копируют или удаляют.',
    placement: 'bottom',
  },
  {
    id: 'template-document',
    route: '/templates?tab=document',
    target: '[data-onboarding-id="template-document-tab"]',
    title: 'Документы и вложения',
    description: 'Документы создаются отдельно от писем, проверяются перед запуском и могут персонализироваться для каждого получателя.',
    placement: 'bottom',
  },
  {
    id: 'template-actions',
    route: '/templates',
    target: '[data-onboarding-id="template-library-toolbar"]',
    title: 'Редактирование и предпросмотр',
    description: 'Перед использованием проверьте тему, текст, переменные и предпросмотр. Для документов дополнительно важны итоговый PDF и расположение полей.',
    placement: 'bottom',
  },
  {
    id: 'chain-create',
    route: '/chains',
    target: '[data-onboarding-id="create-chain"]',
    title: 'Создание цепочки',
    description: 'Новая цепочка открывается как черновик. Она не влияет на активные рассылки, пока не сохранена, опубликована и выбрана в кампании.',
    placement: 'bottom',
  },
  {
    id: 'chain-builder',
    route: '/chains',
    target: '[data-onboarding-id="chain-builder"] .chain-node-block--selected',
    title: 'Схема писем и переходов',
    description: 'Узлы-письма задают контент, а узлы-ссылки фиксируют пользовательские переходы, подписку и отписку.',
    placement: 'bottom',
  },
  {
    id: 'chain-settings',
    route: '/chains',
    target: '[data-onboarding-id="chain-settings"]',
    title: 'Настройки выбранного узла',
    description: 'Для письма выбираются шаблон и документы. Для ссылки задаются подпись, адрес и бизнес-смысл перехода.',
    placement: 'left',
  },
  {
    id: 'chain-publish',
    route: '/chains',
    target: '[data-onboarding-id="chain-publish"]',
    title: 'Сохранение и публикация',
    description: 'Сохранение фиксирует черновик, а публикация делает проверенную версию доступной для новых рассылок.',
    placement: 'bottom',
  },
  {
    id: 'content-finish',
    route: '/templates',
    title: 'Обучение по шаблонам завершено',
    description: 'Вы просмотрели библиотеку писем, документы, генерацию и редакторские проверки. Данные не изменялись.',
  },

  {
    id: 'campaign-intro',
    route: '/campaigns/new?onboarding=1',
    title: 'Создание рассылки',
    description: 'Пять разделов мастера определяют бизнес-контекст, отправителя, получателей, скорость и готовность к запуску.',
  },
  {
    id: 'campaign-finish',
    route: '/?tab=campaign-list',
    title: 'Глава о рассылке завершена',
    description: 'Вы просмотрели все параметры, влияющие на формирование, отправку и проверку кампании. Черновик и отправка не создавались.',
  },

  {
    id: 'analytics-intro',
    route: '/',
    title: 'Контроль и аналитика',
    description: 'Глава показывает, как администратор контролирует отправку, находит проблемы и оценивает бизнес-результат.',
  },
  {
    id: 'analytics-filters',
    route: '/',
    target: '[data-onboarding-id="statistics-filters"]',
    title: 'Период, рассылка и провайдер',
    description: 'Фильтры меняют контекст всех показателей. Перед сравнением результатов проверьте период, кампанию и канал отправки.',
    placement: 'bottom',
  },
  {
    id: 'analytics-summary',
    route: '/',
    target: '[data-onboarding-id="statistics-summary"]',
    title: 'Воронка и проблемные зоны',
    description: 'Сводка помогает увидеть потери между приёмом, доставкой, открытием и переходом, а также найти заинтересованные и проблемные компании.',
    placement: 'bottom',
  },
  {
    id: 'analytics-campaign-metrics',
    route: '/?tab=campaigns',
    target: '[data-onboarding-id="statistics-overview"] .ant-tabs-tab-active',
    title: 'Сравнение рассылок',
    description: 'Показатели рассылок позволяют сравнить доставляемость и вовлечение, не смешивая кампании с разными целями.',
    placement: 'top',
  },
  {
    id: 'analytics-recipients',
    route: '/?tab=recipients',
    target: '[data-onboarding-id="statistics-overview"] .ant-tabs-tab-active',
    title: 'Компании и статусы',
    description: 'Здесь видна история контакта с компаниями: доставка, интерес, проблемы и необходимость следующего действия.',
    placement: 'top',
  },
  {
    id: 'analytics-campaign',
    route: '/?tab=campaign-analytics',
    target: '[data-onboarding-id="statistics-body-campaign-analytics"]',
    title: 'Аналитика конкретной рассылки',
    description: 'Раздел связывает показатели с письмами, ссылками и документами выбранной цепочки и показывает проблемные адреса.',
    placement: 'top',
  },
  {
    id: 'analytics-full',
    route: '/?tab=campaign-full-analytics',
    target: '[data-onboarding-id="statistics-body-campaign-full-analytics"]',
    title: 'Полная аналитика',
    description: 'Полный отчёт объединяет этапы цепочки, действия получателей, материалы, проблемы и рекомендации для следующего контакта.',
    placement: 'top',
  },
  {
    id: 'analytics-consents',
    route: '/?tab=marketing-consents',
    target: '[data-onboarding-id="statistics-consents-summary"]',
    title: 'Подписки и отписки',
    description: 'Согласия и отписки влияют на допустимость дальнейших коммуникаций и должны учитываться при подготовке новых аудиторий.',
    placement: 'top',
  },
  {
    id: 'analytics-finish',
    route: '/',
    title: 'Глава об аналитике завершена',
    description: 'Вы просмотрели управление рассылками, фильтры, воронку, детализацию кампаний, компании и согласия.',
  },

  // Expanded document tutorial. Appended to preserve every persisted index
  // from earlier onboarding versions.
  {
    id: 'document-library',
    route: '/templates?tab=document',
    target: '[data-onboarding-id="document-library-toolbar"]',
    title: 'Библиотека документов',
    description: 'На вкладке хранятся шаблоны вложений, которые затем выбираются в узлах цепочки.',
    details: [
      'Каждый документ создаётся и проверяется отдельно от письма.',
      'Один шаблон можно повторно использовать в разных цепочках.',
      'Готовые документы персонализируются для конкретного получателя.',
    ],
    placement: 'bottom',
  },
  {
    id: 'document-add',
    route: '/templates?tab=document',
    target: '[data-onboarding-id="document-add"]',
    title: 'Создание документа',
    description: 'Кнопка открывает безопасный мастер добавления документа без запуска рассылки.',
    details: [
      'Можно загрузить собственный файл.',
      'Можно взять готовую основу из галереи.',
      'После добавления документ остаётся шаблоном, пока его не выберут в цепочке.',
    ],
    placement: 'bottom',
  },
  {
    id: 'document-formats',
    route: '/templates?tab=document',
    target: '[data-onboarding-id="document-formats"]',
    title: 'Поддерживаемые форматы',
    description: 'Для документов доступны DOCX, PDF и HTML, но возможности редактирования у них различаются.',
    details: [
      'DOCX подходит для редактируемых деловых документов и переменных.',
      'PDF сохраняет готовый внешний вид и требует особенно внимательной проверки полей.',
      'HTML удобен для шаблонов, которые формируются системой.',
    ],
    tip: 'Файл письма и файл документа — разные шаблоны; документ не нужно загружать как письмо.',
    placement: 'bottom',
  },
  {
    id: 'document-source',
    route: '/templates?tab=document',
    target: '[data-onboarding-id="document-source"] > .starter-tile:first-child',
    title: 'Основа документа',
    description: 'В мастере выбирают загрузку своего файла или готовую основу.',
    details: [
      'Загрузка сохраняет структуру исходного документа.',
      'Готовая основа ускоряет старт и затем редактируется как обычный шаблон.',
    ],
    placement: 'left',
  },
  {
    id: 'document-upload',
    route: '/templates?tab=document',
    target: '[data-onboarding-id="document-upload"]',
    title: 'Загрузка исходника',
    description: 'При загрузке система проверит безопасность, извлечёт текст и поля, а затем подготовит предпросмотр.',
    details: [
      'Для DOCX дополнительно проверяются используемые шрифты.',
      'Исходный файл не отправляется автоматически.',
      'После обработки всегда просмотрите получившийся шаблон.',
    ],
    placement: 'right',
  },
  {
    id: 'document-fields',
    route: '/templates?tab=document',
    target: '[data-onboarding-id="document-fields"]',
    title: 'Поля и персонализация',
    description: 'Переменные позволяют сформировать отдельный документ для каждой компании и получателя.',
    details: [
      'Доступны реквизиты компании, контакты и данные получателя.',
      'Вид работ связывает документ с бизнес-контекстом рассылки.',
      'Перед запуском мастер рассылки проверяет сопоставление всех обязательных полей.',
    ],
    placement: 'left',
  },
  {
    id: 'document-preview',
    route: '/templates?tab=document',
    target: '[data-onboarding-id="document-preview"]',
    title: 'Предпросмотр и вёрстка',
    description: 'Итоговый PDF нужно проверить до выбора документа в рассылке.',
    details: [
      'Проверьте количество страниц, переносы и обрезанный текст.',
      'Убедитесь, что шрифты и подписи отображаются правильно.',
      'Посмотрите расположение персональных полей на реальном примере.',
    ],
    tip: 'Если документ должен помещаться на одну страницу, исправьте вёрстку до запуска.',
    placement: 'left',
  },
  {
    id: 'document-chain-use',
    route: '/templates?tab=document',
    target: '[data-onboarding-id="document-chain-use"]',
    title: 'Документ в цепочке',
    description: 'Сам документ не определяет, когда его отправлять: это задаётся в нужном узле цепочки.',
    details: [
      'Выберите письмо в конструкторе цепочки.',
      'Добавьте один или несколько документов в настройках узла.',
      'Проверьте письмо и вложения в тестовой отправке.',
    ],
    placement: 'left',
  },

  // Expanded chain tutorial.
  {
    id: 'chain-name-status',
    route: '/chains',
    target: '[data-onboarding-id="chain-name-status"]',
    title: 'Название и статус цепочки',
    description: 'Название помогает выбрать сценарий в рассылке, а статус показывает, можно ли его использовать.',
    details: [
      'Черновик можно свободно редактировать.',
      'Опубликованная версия доступна в мастере рассылки.',
      'Изменения черновика не меняют уже запущенные рассылки.',
    ],
    placement: 'bottom',
  },
  {
    id: 'chain-add-nodes',
    route: '/chains',
    target: '[data-onboarding-id="chain-add-nodes"]',
    title: 'Добавление писем и переходов',
    description: 'Цепочка строится из узлов-писем и узлов-ссылок, которые добавляются после выбранного письма.',
    details: [
      'Письмо содержит контент и вложения.',
      'Ссылка фиксирует действие получателя.',
      'Следующее письмо создаёт продолжение сценария.',
    ],
    placement: 'bottom',
  },
  {
    id: 'chain-email-template',
    route: '/chains',
    target: '[data-onboarding-id="chain-email-template"]',
    title: 'Шаблон письма в узле',
    description: 'Для каждого узла-письма выбирается заранее подготовленный шаблон.',
    details: [
      'Тема и текст берутся из выбранного шаблона.',
      'Переменные проверяются вместе с данными получателей.',
      'Разные узлы могут использовать разные письма.',
    ],
    placement: 'left',
  },
  {
    id: 'chain-documents',
    route: '/chains',
    target: '[data-onboarding-id="chain-documents"]',
    title: 'Документы у письма',
    description: 'Здесь к конкретному письму цепочки прикрепляются нужные документы.',
    details: [
      'Первое письмо может идти без вложения, а следующее — с документом.',
      'Для каждого получателя формируется персональная версия.',
      'Готовность документов проверяется перед запуском рассылки.',
    ],
    placement: 'left',
  },
  {
    id: 'chain-transitions',
    route: '/chains',
    target: '[data-onboarding-id="chain-transitions"]',
    title: 'Переход к следующему шагу',
    description: 'Переход связывает текущее письмо со ссылкой или следующим письмом.',
    details: [
      'Подпись перехода должна объяснять действие получателю.',
      'Схема помогает проверить, куда ведёт каждая ветка.',
      'Не оставляйте узлы, до которых невозможно дойти.',
    ],
    placement: 'left',
  },
  {
    id: 'chain-link-purpose',
    route: '/chains',
    target: '[data-onboarding-id="chain-link-purpose"]',
    title: 'Назначение ссылки',
    description: 'У ссылки задаётся адрес и бизнес-смысл, который используется в аналитике и правилах согласия.',
    details: [
      'Обычная ссылка ведёт на материал или страницу.',
      'Подписка фиксирует согласие на дальнейшую коммуникацию.',
      'Отписка исключает контакт из последующих отправок.',
    ],
    placement: 'left',
  },
  {
    id: 'chain-save',
    route: '/chains',
    target: '[data-onboarding-id="chain-save"]',
    title: 'Сохранение черновика',
    description: 'Сохранение фиксирует текущую схему, но ещё не делает её доступной для новых рассылок.',
    tip: 'Сохраняйте изменения перед предпросмотром и публикацией.',
    placement: 'bottom',
  },
  {
    id: 'chain-publish-button',
    route: '/chains',
    target: '[data-onboarding-id="chain-publish-button"]',
    title: 'Публикация цепочки',
    description: 'Публикация проверяет схему и делает версию доступной в мастере создания рассылки.',
    details: [
      'Все письма и обязательные переходы должны быть настроены.',
      'После публикации выберите эту цепочку в основной информации рассылки.',
    ],
    placement: 'bottom',
  },

  // Expanded campaign tutorial.
  {
    id: 'campaign-name',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-name"] .ant-form-item-label > label',
    title: 'Название рассылки',
    description: 'Дайте рассылке понятное рабочее название — оно появится в списке, фильтрах и аналитике.',
    tip: 'Название не является темой письма и не показывается получателю.',
    placement: 'right',
  },
  {
    id: 'campaign-chain',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-chain"] .ant-form-item-label > label',
    title: 'Выбор цепочки',
    description: 'Цепочка определяет письма, вложения, ссылки и возможные продолжения сценария.',
    details: [
      'В списке доступны опубликованные цепочки.',
      'Изменить структуру можно в конструкторе цепочек.',
      'После выбора проверьте предпросмотр каждого письма.',
    ],
    placement: 'right',
  },
  {
    id: 'campaign-company',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-company"] .ant-form-item-label > label',
    title: 'Компания',
    description: 'Компания задаёт владельца бизнес-контекста, доступные виды работ и фирменные данные.',
    placement: 'right',
  },
  {
    id: 'campaign-work-type',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-work-type"] .ant-form-item-label > label',
    title: 'Вид работ',
    description: 'Вид работ уточняет предложение и может автоматически подставляться в письмо или документ.',
    tip: 'Если список пуст, сначала добавьте виды работ в настройках компании.',
    placement: 'right',
  },
  {
    id: 'campaign-sender-connection',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-sender-connection"] .ant-form-item-label > label',
    title: 'Подключение отправителя',
    description: 'Выберите проверенный почтовый ящик или API-провайдера.',
    details: [
      'Подключение задаёт адрес отправителя и способ доставки.',
      'Его лимиты действуют на все рассылки через это подключение.',
      'Транспорт подставится автоматически.',
    ],
    placement: 'right',
  },
  {
    id: 'campaign-audience',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-audience"] .ant-form-item-label > label',
    title: 'Сохранённая аудитория',
    description: 'Готовую проверенную аудиторию можно повторно использовать без новой загрузки файла.',
    placement: 'right',
  },
  {
    id: 'campaign-recipient-sources',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-recipient-sources"]',
    title: 'Загрузка или генерация получателей',
    description: 'Получателей можно импортировать из Excel/CSV либо сформировать встроенным инструментом.',
    details: [
      'Одна строка должна описывать одну компанию или контакт.',
      'Проверьте названия столбцов и email до запуска.',
      'Исключения и дубликаты обрабатываются отдельно.',
    ],
    placement: 'right',
  },
  {
    id: 'campaign-recipient-check',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-recipient-check"]',
    title: 'Проверка списка',
    description: 'Таблица показывает, какие контакты готовы к отправке, имеют ошибку или исключены.',
    tip: 'Не запускайте рассылку, пока не понятна причина каждого исключения и ошибки проверки.',
    placement: 'right',
  },
  {
    id: 'campaign-batch-size',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-batch-size"] .ant-form-item-label > label',
    title: 'Размер пакета',
    description: 'Размер пакета задаёт, сколько получателей обрабатывается за один цикл.',
    details: [
      'Меньшие пакеты снижают резкую нагрузку.',
      'Размер должен учитывать лимиты выбранного отправителя.',
    ],
    placement: 'right',
  },
  {
    id: 'campaign-start-at',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-start-at"] .ant-form-item-label > label',
    title: 'Дата и время старта',
    description: 'Укажите фактическое время начала отправки в часовом поясе системы.',
    tip: 'Перед отложенным стартом убедитесь, что подключение и шаблоны не будут изменены.',
    placement: 'right',
  },
  {
    id: 'campaign-interval',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-interval"] .ant-form-item-label > label',
    title: 'Интервал между пакетами',
    description: 'Интервал распределяет отправку во времени и помогает соблюдать лимиты провайдера.',
    placement: 'right',
  },
  {
    id: 'campaign-schedule-preview',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-schedule-preview"]',
    title: 'Прогноз длительности',
    description: 'Прогноз показывает число пакетов и ориентировочную длительность рассылки.',
    tip: 'Сверьте прогноз с рабочим временем получателей и дневным лимитом подключения.',
    placement: 'right',
  },
  {
    id: 'campaign-launch-checks',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-launch-checks"]',
    title: 'Проверка готовности',
    description: 'Перед стартом система соберёт ошибки и предупреждения по всем предыдущим разделам.',
    details: [
      'Проверяются цепочка, шаблоны и документы.',
      'Проверяются получатели и сопоставление переменных.',
      'Ошибки блокируют запуск, предупреждения требуют осознанной проверки.',
    ],
    placement: 'right',
  },
  {
    id: 'campaign-test-email',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-test-email"]',
    title: 'Тестовое письмо',
    description: 'Тестовая отправка позволяет проверить тему, текст, ссылки и вложения на реальном почтовом ящике.',
    tip: 'Откройте письмо и вложения как на компьютере, так и на телефоне.',
    placement: 'right',
  },
  {
    id: 'campaign-start',
    route: '/campaigns/new?onboarding=1',
    target: '[data-onboarding-id="campaign-start"]',
    title: 'Запуск рассылки',
    description: 'Старт создаёт задания на отправку по выбранному расписанию.',
    details: [
      'После запуска следите за прогрессом на вкладке «Рассылки».',
      'Доставку и вовлечение смотрите в «Показателях рассылок».',
      'При росте ошибок поставьте рассылку на паузу и проверьте подключение.',
    ],
    tip: 'Во время обучения кнопка отключена и ничего не отправляет.',
    placement: 'right',
  },

  // Extra analytics explanations.
  {
    id: 'analytics-management-vs-metrics',
    route: '/?tab=campaign-list',
    target: '[data-onboarding-id="statistics-overview"] .ant-tabs-tab-active',
    title: 'Управление и показатели — разные задачи',
    description: '«Рассылки» управляют процессом, а «Показатели рассылок» сравнивают результаты уже выполненных отправок.',
    details: [
      'На вкладке «Рассылки» видны прогресс, попытки и доступные действия.',
      'На вкладке «Показатели» видны доставка, открытия, переходы и согласия.',
    ],
    placement: 'top',
  },
  {
    id: 'analytics-campaign-status',
    route: '/?tab=campaigns',
    target: '[data-onboarding-id="campaign-status-column"]',
    title: 'Статус рассылки',
    description: 'Статус в аналитике повторяет реальное состояние рассылки: в работе, на паузе, завершена, завершена с ошибками или отменена.',
    tip: 'Статус «Завершена с ошибками» означает, что часть получателей не была обработана успешно.',
    placement: 'top',
  },
  {
    id: 'analytics-rates',
    route: '/?tab=campaigns',
    target: '[data-onboarding-id="campaign-delivery-rate-column"]',
    title: 'Как читать проценты',
    description: 'В строке сначала показано абсолютное число, затем доля для этой же рассылки.',
    details: [
      'Доставляемость: доставлено / принято провайдером.',
      'Открываемость: открыто / доставлено.',
      'CTR: переходы / принято провайдером.',
    ],
    tip: 'Сравнивайте рассылки с похожей целью и сопоставимым объёмом.',
    placement: 'top',
  },
];

export const ONBOARDING_CHAPTERS: OnboardingChapterDefinition[] = [
  {
    id: 'general',
    title: 'Общее обучение',
    description: 'Знакомство с основными разделами CampaignFlow.',
    entryRoute: '/',
    scope: 'general',
    stepIds: [
      'welcome',
      'connection-open',
      'template-open',
      'quick-chain',
      'campaign-basics',
      'campaign-sender',
      'campaign-recipients',
      'campaign-schedule',
      'campaign-launch',
      'campaigns-overview',
      'statistics-overview',
      'finish',
    ],
  },
  {
    id: 'companies',
    title: 'Компании',
    description: 'Карточка компании и виды работ.',
    entryRoute: '/companies',
    scope: 'local',
    stepIds: [
      'company-overview',
      'company-details',
      'company-work-types',
    ],
  },
  {
    id: 'connections',
    title: 'Подключения',
    description: 'Отправители, доступы, лимиты и защита доставки.',
    entryRoute: '/connections',
    scope: 'local',
    stepIds: [
      'connection-open',
      'connection-method',
      'connection-details',
      'connection-auth',
      'connection-api-provider',
      'connection-credentials',
      'connection-submit',
      'connection-limits',
      'connection-delivery-guard',
    ],
  },
  {
    id: 'templates',
    title: 'Шаблоны',
    description: 'Письма, документы, генерация и предпросмотр.',
    entryRoute: '/templates',
    scope: 'local',
    stepIds: [
      'content-intro',
      'template-library',
      'template-open',
      'template-format',
      'template-source',
      'template-custom',
      'template-actions',
      'template-document',
      'document-library',
      'document-add',
      'document-formats',
      'document-source',
      'document-upload',
      'document-fields',
      'document-preview',
      'document-chain-use',
      'content-finish',
    ],
  },
  {
    id: 'chains',
    title: 'Цепочки',
    description: 'Письма, переходы и настройки сценария.',
    entryRoute: '/chains',
    scope: 'local',
    stepIds: [
      'chains-overview',
      'chain-create',
      'chain-name-status',
      'chain-builder',
      'chain-add-nodes',
      'chain-email-template',
      'chain-documents',
      'chain-transitions',
      'chain-link-purpose',
      'chain-save',
      'chain-publish-button',
    ],
  },
  {
    id: 'campaign',
    title: 'Создание рассылки',
    description: 'Все параметры от бизнес-контекста до безопасного запуска.',
    entryRoute: '/campaigns/new?onboarding=1',
    scope: 'local',
    stepIds: [
      'campaign-intro',
      'campaign-basics',
      'campaign-name',
      'campaign-chain',
      'campaign-company',
      'campaign-work-type',
      'campaign-sender',
      'campaign-sender-connection',
      'campaign-recipients',
      'campaign-audience',
      'campaign-recipient-sources',
      'campaign-recipient-check',
      'campaign-schedule',
      'campaign-batch-size',
      'campaign-start-at',
      'campaign-interval',
      'campaign-schedule-preview',
      'campaign-launch',
      'campaign-launch-checks',
      'campaign-test-email',
      'campaign-start',
    ],
  },
  {
    id: 'analytics',
    title: 'Контроль и аналитика',
    description: 'Мониторинг, проблемы, результат и согласия.',
    entryRoute: '/',
    scope: 'local',
    stepIds: [
      'analytics-intro',
      'campaigns-overview',
      'analytics-management-vs-metrics',
      'analytics-filters',
      'analytics-summary',
      'analytics-campaign-metrics',
      'analytics-campaign-status',
      'analytics-rates',
      'analytics-recipients',
      'analytics-campaign',
      'analytics-full',
      'analytics-consents',
      'analytics-finish',
    ],
  },
];

export function getOnboardingChapter(chapterId: OnboardingChapterId) {
  return ONBOARDING_CHAPTERS.find((chapter) => chapter.id === chapterId);
}

export function getOnboardingChapterSteps(chapterId: OnboardingChapterId) {
  const chapter = getOnboardingChapter(chapterId);
  if (!chapter) return [];
  const byId = new Map(ONBOARDING_STEPS.map((step) => [step.id, step]));
  return chapter.stepIds
    .map((stepId) => byId.get(stepId))
    .filter((step): step is OnboardingStepDefinition => Boolean(step));
}

export function findOnboardingChapterForStep(stepId?: string): OnboardingChapterId {
  if (stepId) {
    const match = ONBOARDING_CHAPTERS.find((chapter) => chapter.stepIds.includes(stepId));
    if (match) return match.id;
  }
  return 'general';
}
